eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: pass@word1
  jpa:
    database: mysql
  application:
    name: Company-Application

server:
  port: 9005 

   