eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: stock-application
          uri: lb://Stock-Application
          predicates:
            - Path=/stock/**
          filters:
            - name: CircuitBreaker
              args:
                name: stock-application
                fallbackuri: forward:/stockFallBack
        - id: company-application
          uri: lb://Company-Application
          predicates:
            - Path=/api/v1.0/market/company/**
          filters:
            - name: CircuitBreaker
              args:
                name: company-application
                fallbackuri: forward:/companyFallback



server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  